version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "automated"
    reviewers:
      - "gourav-007"
    assignees:
      - "gourav-007"
