name: regression-suite

on:
  push:
    branches:
      - main
      
  pull_request:
    types: [opened, synchronized]
    
  schedule: 
    # Schedule the job to run at 04:00 on Saturday.
    - cron: '0 4 * * 6'

  workflow_dispatch: 
    inputs:
      text1:
        description: 'Do you really want to trigger workflow?[yes/no]'
        default: no
        required: true
        type: string
        
      text2:
        description: 'Enter your userid'
        default: '@gourav-007'
        required: true
        type: string

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  test:
    needs: build #Wait for 'build' to be completed.
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Running Tests
        run: mvn clean test 
      - name: Badge Action
        uses: emibcn/badge-action@v2.0.3
        with:
          path: '.github/badges/coverage.svg'
    
      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      #- name: Update dependency graph
       # uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
